apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.crossplane.providerConfigRef }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.crossplane.credentials.namespace }}
      name: {{ .Values.crossplane.credentials.name }}
      key: {{ .Values.crossplane.credentials.key }}
